import { FeedbackItem, FeatureRequest } from '@/types';

export const SEED_FEEDBACK: FeedbackItem[] = [
  {
    id: 'fb-001',
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-03-01T09:00:00Z',
    customerName: 'Alicia Morgan',
    companyName: 'Vertex Analytics',
    dealStage: 'closed-lost',
    dealValue: 85000,
    salesRep: 'Jordan Kim',
    painPoint: 'Cannot connect to Salesforce and HubSpot simultaneously. Dual CRM integrations are blocking our sales ops team from adopting the platform.',
    category: 'integration',
    frequency: 'critical',
    urgency: 5,
    revenueImpact: 85000,
    tags: ['salesforce', 'hubspot', 'crm', 'integration'],
    status: 'in-progress',
    notes: 'Primary reason for lost deal. Competitor (Gong) supports both.',
  },
  {
    id: 'fb-002',
    createdAt: '2024-03-03T11:30:00Z',
    updatedAt: '2024-03-04T08:00:00Z',
    customerName: 'Derek Patel',
    companyName: 'Meridian Capital',
    dealStage: 'negotiation',
    dealValue: 120000,
    salesRep: 'Sam Rivera',
    painPoint: 'Dashboard load times exceed 8 seconds on large datasets (500k+ rows). Finance team needs sub-2s response times for compliance reporting.',
    category: 'performance',
    frequency: 'frequent',
    urgency: 5,
    revenueImpact: 120000,
    tags: ['performance', 'dashboard', 'compliance', 'large-data'],
    status: 'reviewed',
    linkedFeatureId: 'feat-002',
  },
  {
    id: 'fb-003',
    createdAt: '2024-03-05T14:00:00Z',
    updatedAt: '2024-03-05T14:00:00Z',
    customerName: 'Priya Nair',
    companyName: 'CloudScale Inc',
    dealStage: 'qualified',
    dealValue: 42000,
    salesRep: 'Jordan Kim',
    painPoint: 'No native Slack integration. Team needs to receive alerts and digests directly in Slack channels without setting up webhooks manually.',
    category: 'integration',
    frequency: 'frequent',
    urgency: 3,
    revenueImpact: 42000,
    tags: ['slack', 'notifications', 'alerts', 'integration'],
    status: 'new',
  },
  {
    id: 'fb-004',
    createdAt: '2024-03-06T10:00:00Z',
    updatedAt: '2024-03-07T09:00:00Z',
    customerName: 'Marcus Webb',
    companyName: 'TerraForm SaaS',
    dealStage: 'closed-lost',
    dealValue: 65000,
    salesRep: 'Alex Chen',
    painPoint: 'Pricing model is seat-based but their team fluctuates. They need consumption or usage-based pricing to control costs during ramp-up.',
    category: 'pricing',
    frequency: 'critical',
    urgency: 5,
    revenueImpact: 65000,
    tags: ['pricing', 'usage-based', 'seats', 'flexibility'],
    status: 'reviewed',
    notes: 'Second deal this quarter lost due to seat-based pricing.',
  },
  {
    id: 'fb-005',
    createdAt: '2024-03-08T15:30:00Z',
    updatedAt: '2024-03-08T15:30:00Z',
    customerName: 'Sarah Okonkwo',
    companyName: 'Beacon Health',
    dealStage: 'proposal',
    dealValue: 200000,
    salesRep: 'Sam Rivera',
    painPoint: 'No HIPAA BAA available and no audit log export. Healthcare verticals cannot deploy without these — a complete blocker.',
    category: 'security',
    frequency: 'critical',
    urgency: 5,
    revenueImpact: 200000,
    tags: ['hipaa', 'compliance', 'audit-log', 'healthcare'],
    status: 'in-progress',
    linkedFeatureId: 'feat-003',
    notes: 'Major enterprise deal blocked. Need legal + engineering alignment.',
  },
  {
    id: 'fb-006',
    createdAt: '2024-03-09T09:00:00Z',
    updatedAt: '2024-03-09T09:00:00Z',
    customerName: 'Tom Fischer',
    companyName: 'Agile Ops Co',
    dealStage: 'closed-won',
    dealValue: 35000,
    salesRep: 'Alex Chen',
    painPoint: 'Onboarding took 3 weeks due to lack of guided setup wizard. In-app walkthroughs would have cut this to 3 days.',
    category: 'onboarding',
    frequency: 'occasional',
    urgency: 3,
    revenueImpact: 15000,
    tags: ['onboarding', 'wizard', 'setup', 'ux'],
    status: 'reviewed',
  },
  {
    id: 'fb-007',
    createdAt: '2024-03-10T13:00:00Z',
    updatedAt: '2024-03-10T13:00:00Z',
    customerName: 'Linda Zhao',
    companyName: 'NovaTech Labs',
    dealStage: 'closed-lost',
    dealValue: 55000,
    salesRep: 'Jordan Kim',
    painPoint: 'Salesforce integration is read-only. They need bi-directional sync to push enriched contact data back into their CRM.',
    category: 'integration',
    frequency: 'critical',
    urgency: 4,
    revenueImpact: 55000,
    tags: ['salesforce', 'bi-directional', 'sync', 'crm'],
    status: 'new',
  },
  {
    id: 'fb-008',
    createdAt: '2024-03-11T10:00:00Z',
    updatedAt: '2024-03-12T11:00:00Z',
    customerName: 'Carlos Vega',
    companyName: 'RetailEdge Corp',
    dealStage: 'negotiation',
    dealValue: 78000,
    salesRep: 'Sam Rivera',
    painPoint: 'No mobile app. Field sales reps need iOS access to view dashboards and log activity from their phones during client visits.',
    category: 'mobile',
    frequency: 'frequent',
    urgency: 4,
    revenueImpact: 78000,
    tags: ['mobile', 'ios', 'field-sales', 'app'],
    status: 'reviewed',
    linkedFeatureId: 'feat-004',
  },
  {
    id: 'fb-009',
    createdAt: '2024-03-12T14:30:00Z',
    updatedAt: '2024-03-12T14:30:00Z',
    customerName: 'Nina Bauer',
    companyName: 'Pulse Metrics',
    dealStage: 'qualified',
    dealValue: 28000,
    salesRep: 'Alex Chen',
    painPoint: 'Report export only supports CSV. Need PDF and PowerPoint export for executive presentations — currently exporting and manually reformatting.',
    category: 'reporting',
    frequency: 'frequent',
    urgency: 3,
    revenueImpact: 28000,
    tags: ['export', 'pdf', 'powerpoint', 'reporting'],
    status: 'new',
  },
  {
    id: 'fb-010',
    createdAt: '2024-03-13T09:00:00Z',
    updatedAt: '2024-03-14T10:00:00Z',
    customerName: 'James Okafor',
    companyName: 'Finvest Group',
    dealStage: 'closed-lost',
    dealValue: 150000,
    salesRep: 'Jordan Kim',
    painPoint: 'API rate limits too restrictive (100 req/min). High-volume trading data ingestion requires 10,000+ req/min. Cannot build the pipeline.',
    category: 'api',
    frequency: 'critical',
    urgency: 5,
    revenueImpact: 150000,
    tags: ['api', 'rate-limits', 'throughput', 'data-ingestion'],
    status: 'reviewed',
    notes: 'Enterprise tier needed with configurable rate limits.',
  },
  {
    id: 'fb-011',
    createdAt: '2024-03-14T11:00:00Z',
    updatedAt: '2024-03-14T11:00:00Z',
    customerName: 'Rachel Torres',
    companyName: 'SparkFlow AI',
    dealStage: 'proposal',
    dealValue: 45000,
    salesRep: 'Sam Rivera',
    painPoint: 'Dashboard builder is overly complex. New users abandon onboarding because it requires 15+ steps to create a basic dashboard.',
    category: 'ux',
    frequency: 'frequent',
    urgency: 3,
    revenueImpact: 22000,
    tags: ['ux', 'dashboard', 'complexity', 'onboarding'],
    status: 'new',
  },
  {
    id: 'fb-012',
    createdAt: '2024-03-15T13:00:00Z',
    updatedAt: '2024-03-15T13:00:00Z',
    customerName: 'Ben Nakamura',
    companyName: 'Skyline Digital',
    dealStage: 'closed-won',
    dealValue: 62000,
    salesRep: 'Alex Chen',
    painPoint: 'Pricing tiers jump from $500/mo to $2000/mo with no mid-tier. Lost 3 SMB prospects who needed features in the Pro tier but could not justify 4x cost.',
    category: 'pricing',
    frequency: 'frequent',
    urgency: 4,
    revenueImpact: 45000,
    tags: ['pricing', 'tiers', 'smb', 'mid-market'],
    status: 'reviewed',
  },
  {
    id: 'fb-013',
    createdAt: '2024-03-16T10:00:00Z',
    updatedAt: '2024-03-16T10:00:00Z',
    customerName: 'Fatima Al-Hassan',
    companyName: 'GrowthStack',
    dealStage: 'qualified',
    dealValue: 32000,
    salesRep: 'Jordan Kim',
    painPoint: 'Query performance degrades significantly when joining 4+ tables. Complex analytics queries time out after 30 seconds.',
    category: 'performance',
    frequency: 'frequent',
    urgency: 4,
    revenueImpact: 32000,
    tags: ['performance', 'query', 'joins', 'timeout'],
    status: 'new',
  },
  {
    id: 'fb-014',
    createdAt: '2024-03-17T14:00:00Z',
    updatedAt: '2024-03-17T14:00:00Z',
    customerName: 'Owen Clark',
    companyName: 'DataBridge LLC',
    dealStage: 'proposal',
    dealValue: 88000,
    salesRep: 'Sam Rivera',
    painPoint: 'No REST webhook support for real-time event push. They need to trigger downstream workflows when data conditions are met — polling is too slow.',
    category: 'api',
    frequency: 'critical',
    urgency: 4,
    revenueImpact: 60000,
    tags: ['api', 'webhooks', 'real-time', 'events'],
    status: 'in-progress',
    linkedFeatureId: 'feat-005',
  },
  {
    id: 'fb-015',
    createdAt: '2024-03-18T09:00:00Z',
    updatedAt: '2024-03-18T09:00:00Z',
    customerName: 'Ingrid Svensson',
    companyName: 'NorthLight SaaS',
    dealStage: 'negotiation',
    dealValue: 95000,
    salesRep: 'Alex Chen',
    painPoint: 'No Android mobile app. Half their sales team uses Android devices and cannot use the iOS-only client. They need platform parity.',
    category: 'mobile',
    frequency: 'critical',
    urgency: 4,
    revenueImpact: 47000,
    tags: ['mobile', 'android', 'platform-parity', 'field-sales'],
    status: 'new',
  },
];

export const SEED_FEATURES: FeatureRequest[] = [
  {
    id: 'feat-001',
    title: 'Dual CRM Integration (Salesforce + HubSpot)',
    description: 'Enable simultaneous, bi-directional sync with both Salesforce and HubSpot from a single workspace.',
    category: 'integration',
    status: 'in-progress',
    linkedFeedbackIds: ['fb-001', 'fb-007'],
    totalRevenueImpact: 140000,
    requestCount: 2,
    priority: 95,
    createdAt: '2024-03-02T08:00:00Z',
    updatedAt: '2024-03-10T12:00:00Z',
    assignee: 'Eng Team Alpha',
    estimatedEffort: 'xl',
  },
  {
    id: 'feat-002',
    title: 'High-Volume Query Performance Optimizer',
    description: 'Implement query result caching, columnar storage, and smart pagination for 500k+ row datasets.',
    category: 'performance',
    status: 'planned',
    linkedFeedbackIds: ['fb-002', 'fb-013'],
    totalRevenueImpact: 152000,
    requestCount: 2,
    priority: 90,
    createdAt: '2024-03-04T09:00:00Z',
    updatedAt: '2024-03-13T10:00:00Z',
    assignee: 'Eng Team Beta',
    estimatedEffort: 'l',
  },
  {
    id: 'feat-003',
    title: 'HIPAA Compliance Package (BAA + Audit Logs)',
    description: 'Full HIPAA BAA agreement, audit log export (SOC2 compatible), and PHI data masking controls.',
    category: 'security',
    status: 'in-progress',
    linkedFeedbackIds: ['fb-005'],
    totalRevenueImpact: 200000,
    requestCount: 1,
    priority: 98,
    createdAt: '2024-03-09T10:00:00Z',
    updatedAt: '2024-03-16T09:00:00Z',
    assignee: 'Security Team',
    estimatedEffort: 'xl',
  },
  {
    id: 'feat-004',
    title: 'Mobile App (iOS + Android)',
    description: 'Native mobile clients for iOS and Android with offline mode, push notifications, and field logging.',
    category: 'mobile',
    status: 'planned',
    linkedFeedbackIds: ['fb-008', 'fb-015'],
    totalRevenueImpact: 125000,
    requestCount: 2,
    priority: 85,
    createdAt: '2024-03-12T08:00:00Z',
    updatedAt: '2024-03-15T11:00:00Z',
    assignee: 'Mobile Team',
    estimatedEffort: 'xl',
  },
  {
    id: 'feat-005',
    title: 'Webhook & Real-Time Event System',
    description: 'REST webhook endpoints with payload templating, retry logic, and an event stream API.',
    category: 'api',
    status: 'in-progress',
    linkedFeedbackIds: ['fb-010', 'fb-014'],
    totalRevenueImpact: 210000,
    requestCount: 2,
    priority: 92,
    createdAt: '2024-03-14T08:00:00Z',
    updatedAt: '2024-03-17T14:00:00Z',
    assignee: 'Eng Team Alpha',
    estimatedEffort: 'l',
  },
];
